# Generated by Django 5.2.17 on 2026-09-21 14:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_project'),
    ]

    operations = [
        migrations.CreateModel(
            name='Education',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('institution_name', models.CharField(max_length=255)),
                ('level', models.CharField(choices=[('elementary', 'Elementary School'), ('junior_high', 'Junior High School'), ('senior_high', 'Senior High School'), ('diploma', 'Diploma'), ('bachelor', "Bachelor's Degree"), ('master', "Master's Degree"), ('doctorate', 'Doctorate')], default='bachelor', max_length=20)),
                ('field_of_study', models.CharField(blank=True, max_length=255, null=True)),
                ('gpa', models.DecimalField(blank=True, decimal_places=2, help_text='e.g. 3.75', max_digits=4, null=True)),
                ('start_year', models.PositiveIntegerField()),
                ('end_year', models.PositiveIntegerField(blank=True, null=True)),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-start_year'],
            },
        ),
    ]
